// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3588.DeepSpaceCode.subsystems;


import org.usfirst.frc3588.DeepSpaceCode.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
import edu.wpi.first.wpilibj.command.*;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import com.ctre.phoenix.motorcontrol.can.WPI_VictorSPX;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Chassis extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private WPI_TalonSRX rightMotor1;
    private WPI_VictorSPX leftMotor2;
    private WPI_TalonSRX leftMotor1;
    private WPI_TalonSRX rightMotor2;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public Chassis() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        rightMotor1 = new WPI_TalonSRX(2);
        
        
        
        leftMotor2 = new WPI_VictorSPX(7);
        
        
        
        leftMotor1 = new WPI_TalonSRX(10);
        
        
        
        rightMotor2 = new WPI_TalonSRX(3);
        
        
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new Drive());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // ** need to adjust for motors moving in opposite directions

    

    //  public void drive(double leftSpeed, double rightSpeed){
    //     leftMotor1.set(leftSpeed);
    //     leftMotor2.set(-1 * leftSpeed);
    //     rightMotor1.set(rightSpeed);
    //     rightMotor2.set(-1 * rightSpeed);
    // //     ttoLeft.set(leftSpeed);
    // //     ttoRight.set(rightSpeed);
    // }

    public void setLeftMotor1Speed(double speed) {
        leftMotor1.set(speed);
    }

    public void setLeftMotor2Speed(double speed) {
        leftMotor2.set(speed);
    }

    public void setRightMotor1Speed(double speed) {
        rightMotor1.set(speed);
    }

    public void setRightMotor2Speed(double speed) {
        rightMotor2.set(speed);
    }

    public void driveStraight(double speed) {
        setLeftMotor1Speed(speed);
        setLeftMotor2Speed(-1 * speed);
        setRightMotor1Speed(speed);
        setRightMotor2Speed(-1 * speed);
    }
    // public void detectLine() {

    // }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    //new line
}

