    // RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc3588.DeepSpaceCode;

import org.usfirst.frc3588.DeepSpaceCode.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;

/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public Joystick leftJoystick;
    public JoystickButton manualClimbingButton;
    public Joystick rightJoystick;
    public JoystickButton hatchTopBtn;
    public JoystickButton hatchMiddleBtn;
    public JoystickButton cargoMiddleBtn;
    public JoystickButton cargoTopBtn;
    public Joystick operatorJoystick;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        operatorJoystick = new Joystick(2);
        
        cargoTopBtn = new JoystickButton(operatorJoystick, 6);
        cargoTopBtn.whenPressed(new CargoTop());
        cargoMiddleBtn = new JoystickButton(operatorJoystick, 5);
        cargoMiddleBtn.whenPressed(new CargoMiddle());
        hatchMiddleBtn = new JoystickButton(operatorJoystick, 3);
        hatchMiddleBtn.whenPressed(new HatchMiddle());
        hatchTopBtn = new JoystickButton(operatorJoystick, 4);
        hatchTopBtn.whenPressed(new HatchTop());
        rightJoystick = new Joystick(1);
        
        manualClimbingButton = new JoystickButton(rightJoystick, 1);
        manualClimbingButton.whileHeld(new ManualClimbing());
        leftJoystick = new Joystick(0);
        


        // SmartDashboard Buttons
        SmartDashboard.putData("Drive", new Drive());
        SmartDashboard.putData("OpenCloseCommand", new OpenCloseCommand());
        SmartDashboard.putData("ManualClimbing", new ManualClimbing());
        SmartDashboard.putData("HatchTop", new HatchTop());
        SmartDashboard.putData("HatchMiddle", new HatchMiddle());
        SmartDashboard.putData("CargoTop", new CargoTop());
        SmartDashboard.putData("CargoMiddle", new CargoMiddle());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getleftJoystick() {
        return leftJoystick;
    }

    public Joystick getrightJoystick() {
        return rightJoystick;
    }

    public Joystick getoperatorJoystick() {
        return operatorJoystick;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

